## 06-3. 데이터 추출

In [1]:
import pandas as pd
import numpy as np

mpg = pd.read_csv('mpg.csv')
mpg_mod = mpg.copy()
mpg_mod

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,category
0,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact
1,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact
2,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact
3,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact
4,audi,a4,2.8,1999,6,auto(l5),f,16,26,p,compact
...,...,...,...,...,...,...,...,...,...,...,...
229,volkswagen,passat,2.0,2008,4,auto(s6),f,19,28,p,midsize
230,volkswagen,passat,2.0,2008,4,manual(m6),f,21,29,p,midsize
231,volkswagen,passat,2.8,1999,6,auto(l5),f,16,26,p,midsize
232,volkswagen,passat,2.8,1999,6,manual(m5),f,18,26,p,midsize
233,volkswagen,passat,3.6,2008,6,auto(s6),f,17,26,p,midsize

In [2]:
# 혼자서 해보기 
# Q1. mpg데이터에서 category,cty를 추출해 새 변수에 대입. 새 변수의 일부를 출력해서 확인
new_df = mpg_mod[['category','cty']]
new_df.head()

# Q2. 종류에 따른 연비체크. 카테고리 'suv','compact' 자동차중 어떤 차의 도시연비 평균이 더 좋을까?
suv_mean = mpg_mod.query("category in ['suv']").agg(cty_mean = ('cty','mean')).iloc[0,0]
compact_mean = mpg_mod.query("category in ['compact']").agg(cty_mnea = ('cty','mean')).iloc[0,0]

if suv_mean >= compact_mean:
    print(f'suv가 더 연비가 높습니다. suv:{suv_mean:.2f}, compact:{compact_mean:.2f}')
else:
    print(f'compact 가 더 연비가 높습니다. compact:{compact_mean:.2f}, suv:{suv_mean:.2f}')

compact 가 더 연비가 높습니다. compact:20.13, suv:13.50

# 06-4. 데이터 정렬

In [3]:
# 혼자서 해보기
# Q1. 'audi'에서 생산한 차중 어떤 모델의 hwy가 높은지 알고싶다 hwy 1-5위에 해당하는 데이터 출력
audi_hwy = mpg_mod.query('manufacturer == "audi"').sort_values('hwy',ascending=False).head()
audi_hwy

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,category
2,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact
3,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact
1,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact
0,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact
9,audi,a4 quattro,2.0,2008,4,manual(m6),4,20,28,p,compact

## 06-5. 파생변수 추가하기

In [4]:
import pandas as pd
import numpy as np

exam = pd.read_csv('exam.csv')
exam = exam.assign(total = exam['math'] + exam['english']+ exam['science'])     # 추가
exam = exam.assign(test = np.where(exam['science'] >= 60,'pass','fail'))        # numpy를 이용해 추가할수있다
exam = exam.assign(test_mean = lambda x: x['total']/3)                          # lambda함수를 쓰는방법도 있다
exam

    id  nclass  math  english  science  total  test  test_mean
0    1       1    50       98       50    198  fail  66.000000
1    2       1    60       97       60    217  pass  72.333333
2    3       1    45       86       78    209  pass  69.666667
3    4       1    30       98       58    186  fail  62.000000
4    5       2    25       80       65    170  pass  56.666667
5    6       2    50       89       98    237  pass  79.000000
6    7       2    80       90       45    215  fail  71.666667
7    8       2    90       78       25    193  fail  64.333333
8    9       3    20       98       15    133  fail  44.333333
9   10       3    50       98       45    193  fail  64.333333
10  11       3    65       65       65    195  pass  65.000000
11  12       3    45       85       32    162  fail  54.000000
12  13       4    46       98       65    209  pass  69.666667
13  14       4    48       87       12    147  fail  49.000000
14  15       4    75       56       78    209  pass  69.666667
15  16       4    58       98       65    221  pass  73.666667
16  17       5    65       68       98    231  pass  77.000000
17  18       5    80       78       90    248  pass  82.666667
18  19       5    89       68       87    244  pass  81.333333
19  20       5    78       83       58    219  fail  73.000000

In [5]:
# 혼자서 해보기
# Q1. mpg복사본을 만들고 cty와 hwy를 더한 합산연비를 추가
mpg_copy = mpg.copy()
mpg_copy = mpg_copy.assign(total = lambda x : x['cty']+x['hwy'])

# # Q2. 앞에서 합산연비를 2로 나눠 평균연비변수 추가
mpg_copy = mpg_copy.assign(total_mean = lambda x : x['total'] /2 )

# # Q3. 평균연비가 가장 높은 자동차 3종의 데이터 출력
print(mpg_copy.sort_values('total_mean',ascending=False).head(3))   #폭스바겐 비틀, 제타타

# Q4. 1-3번 문제를 하나로 연결한 판다스구문을 만들어서 실행해보라. mpg원본사용
mpg = mpg.assign(total = lambda x: x['cty']+ x['hwy'], total_mean = lambda x: x['total']/2).sort_values('total_mean',ascending=False).head(3)

    manufacturer       model  displ  year  cyl       trans drv  cty  hwy fl  \
221   volkswagen  new beetle    1.9  1999    4  manual(m5)   f   35   44  d
212   volkswagen       jetta    1.9  1999    4  manual(m5)   f   33   44  d
222   volkswagen  new beetle    1.9  1999    4    auto(l4)   f   29   41  d

       category  total  total_mean
221  subcompact     79        39.5
212     compact     77        38.5
222  subcompact     70        35.0

## 06-6. 그룹별로 출력

In [6]:
# 연습 : 제조회사별로 'suv'자동차의 도시연비 고속연비 합산연비를 구해 그 평균을 내림차순으로 정렬하고 1-5위까지 출력
mpg = pd.read_csv('mpg.csv')
mpg.assign(total = (mpg['cty'] + mpg['hwy'])/2).query('category == "suv"').groupby('manufacturer').agg(total_mean = ('total','mean')).sort_values('total_mean',ascending=False).head()

              total_mean
manufacturer
subaru         21.916667
toyota         16.312500
nissan         15.875000
mercury        15.625000
jeep           15.562500

In [ ]:
#06-7. 혼자서 해보기
fuel = pd.DataFrame({'fl':['c','d','e','p','r'], 'price_fl' : [2.35,2.38,2.11,2.76,2.22]})
# q1
mpg = pd.merge(mpg,fuel,how='left',on='fl')

# q2
mpg[['model','fl','price_fl']].head()

  model fl  price_fl
0    a4  p      2.76
1    a4  p      2.76
2    a4  p      2.76
3    a4  p      2.76
4    a4  p      2.76

In [ ]:
# 분석도전
md = pd.read_csv('midwest.csv')
md

,PID,county,state,area,poptotal,popdensity,popwhite,popblack,popamerindian,popasian,...,percollege,percprof,poppovertyknown,percpovertyknown,percbelowpoverty,percchildbelowpovert,percadultpoverty,percelderlypoverty,inmetro,category
0,561,ADAMS,IL,0.052,66090,1270.961540,63917,1702,98,249,...,19.631392,4.355859,63628,96.274777,13.151443,18.011717,11.009776,12.443812,0,AAR
1,562,ALEXANDER,IL,0.014,10626,759.000000,7054,3496,19,48,...,11.243308,2.870315,10529,99.087145,32.244278,45.826514,27.385647,25.228976,0,LHR
2,563,BOND,IL,0.022,14991,681.409091,14477,429,35,16,...,17.033819,4.488572,14235,94.956974,12.068844,14.036061,10.852090,12.697410,0,AAR
3,564,BOONE,IL,0.017,30806,1812.117650,29344,127,46,150,...,17.278954,4.197800,30337,98.477569,7.209019,11.179536,5.536013,6.217047,1,ALU
4,565,BROWN,IL,0.018,5836,324.222222,5264,547,14,5,...,14.475999,3.367680,4815,82.505140,13.520249,13.022889,11.143211,19.200000,0,AAR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
432,3048,WAUKESHA,WI,0.034,304715,8962.205880,298313,1096,672,2699,...,35.396784,7.667090,299802,98.387674,3.121060,3.785820,2.590061,4.085479,1,HLU
433,3049,WAUPACA,WI,0.045,46104,1024.533330,45695,22,125,92,...,16.549869,3.138596,44412,96.330036,8.488697,10.071411,6.953799,10.338641,0,AAR
434,3050,WAUSHARA,WI,0.037,19385,523.918919,19094,29,70,43,...,15.064584,2.620907,19163,98.854785,13.786985,20.050708,11.695784,11.804558,0,AAR
435,3051,WINNEBAGO,WI,0.035,140320,4009.142860,136822,697,685,1728,...,24.995504,5.659847,133950,95.460376,8.804031,10.592031,8.660587,6.661094,1,HAU
436,3052,WOOD,WI,0.048,73605,1533.437500,72157,90,481,722,...,21.666382,4.583725,72685,98.750085,8.525831,11.162997,7.375656,7.882918,0,AAR

In [26]:
# 1. 전체인구대비 미성년 인구 백분율 변수추가. popadults 성인인구, poptotal전체인구
md[['popadults','poptotal']]

#md['pop_child'] = (md['poptotal'] - md['popadult']) / md['poptotal']

#2. 미성년인구 백분율이 높은 상위5개 출력
#3. 40%이상 large 30-40 middle 30%이상 small 비율등급 추가
#4. popasian은 아시아인 인구. 전체인구대비 아시아인 인구 백분율을 추가 하위10개 지역의 state,country,아시아인구 백분율 출력

     popadults  poptotal
0        43298     66090
1         6724     10626
2         9669     14991
3        19272     30806
4         3979      5836
..         ...       ...
432     195837    304715
433      30109     46104
434      13316     19385
435      88960    140320
436      46796     73605

[437 rows x 2 columns]